//REST client plugin test

//get person
GET http://localhost:3001/api/persons/1

###

//delete person
DELETE http://localhost:3001/api/persons/1

###

//add person
POST http://localhost:3001/api/persons 
Content-Type: application/json

{
"name": "Beelzebub",
"number": "666"
}


